name:                binary-generic-combinators
version:             0.4.0.0
github:              "0xd34df00d/binary-generic-combinators"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2021 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/binary-generic-combinators#readme>

dependencies:
- base >= 4.7 && < 5
- binary

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  binary-generic-combinators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-generic-combinators
